inherit_from: .rubocop_todo.yml

require: 
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec


AllCops:
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'config/**/*'
    - 'spec/**/*'

Metrics:
  Exclude:
    - "app/controllers/employees_controller.rb"

Metrics/LineLength:
  Max: 140

Metrics/BlockLength:
  Exclude:
    - config/**/*
    - spec/**/*

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*

Style/Documentation:
  Enabled: false