inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - "db/**/*"
    - "script/**/*"
    - "bin/**/*"
    - "node_modules/**/*"
    - "config/**/*"

# All the following cops are not part of the coding standard so they are disabled
Metrics:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/Documentation:
  Enabled: false

RSpec:
  Enabled: false

# There isn't a line length limit in the coding so it is set to 165 characters
Layout/LineLength:
  Max: 165
