inherit_from: .rubocop_todo.yml

require: 
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec


AllCops:
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'config/**/*'
    - 'spec/**/*'

Metrics:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 165