release: rake db:migrate
heroku config:set AWS_ACCESS_KEY_ID=AKIA5AQTLGYVQAIIXCB2 AWS_SECRET_ACCESS_KEY=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
heroku config:set S3_BUCKET_NAME=membershpe-profile-pictures